// Mocks generated by Mockito 5.4.4 from annotations
// in smart_wallet/test/features/budgets/data/repositories/budget_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_wallet/features/budgets/data/datasources/budget_local_data_source.dart'
    as _i2;
import 'package:smart_wallet/features/budgets/domain/models/budget.dart' as _i4;
import 'package:smart_wallet/features/budgets/domain/models/goal.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BudgetLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetLocalDataSource extends _i1.Mock
    implements _i2.BudgetLocalDataSource {
  MockBudgetLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Budget>> getAllBudgets() => (super.noSuchMethod(
        Invocation.method(
          #getAllBudgets,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Budget>>.value(<_i4.Budget>[]),
      ) as _i3.Future<List<_i4.Budget>>);

  @override
  _i3.Future<_i4.Budget?> getBudgetByCategory(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudgetByCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<_i4.Budget?>.value(),
      ) as _i3.Future<_i4.Budget?>);

  @override
  _i3.Future<void> addBudget(_i4.Budget? budget) => (super.noSuchMethod(
        Invocation.method(
          #addBudget,
          [budget],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateBudget(_i4.Budget? budget) => (super.noSuchMethod(
        Invocation.method(
          #updateBudget,
          [budget],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBudget(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBudget,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Goal>> getAllGoals() => (super.noSuchMethod(
        Invocation.method(
          #getAllGoals,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Goal>>.value(<_i5.Goal>[]),
      ) as _i3.Future<List<_i5.Goal>>);

  @override
  _i3.Future<void> addGoal(_i5.Goal? goal) => (super.noSuchMethod(
        Invocation.method(
          #addGoal,
          [goal],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateGoal(_i5.Goal? goal) => (super.noSuchMethod(
        Invocation.method(
          #updateGoal,
          [goal],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteGoal(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteGoal,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
