// Mocks generated by Mockito 5.4.4 from annotations
// in smart_wallet/test/features/transactions/data/repositories/transaction_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_wallet/features/transactions/data/datasources/transaction_local_data_source.dart'
    as _i2;
import 'package:smart_wallet/features/transactions/domain/models/category.dart'
    as _i5;
import 'package:smart_wallet/features/transactions/domain/models/transaction.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TransactionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionLocalDataSource extends _i1.Mock
    implements _i2.TransactionLocalDataSource {
  MockTransactionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Transaction>> getAllTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getAllTransactions,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<void> addTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTransaction,
          [transaction],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [transaction],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Transaction>> getTransactionsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<List<_i4.Transaction>> getTransactionsByCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsByCategory,
          [categoryId],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<List<_i4.Transaction>> getMonthlyTransactions(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyTransactions,
          [
            year,
            month,
          ],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<List<_i5.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Category>>.value(<_i5.Category>[]),
      ) as _i3.Future<List<_i5.Category>>);

  @override
  _i3.Future<void> addCategory(_i5.Category? category) => (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
